# service.yml
apiVersion: v1
kind: Service
metadata:
  name: livezilla-web
spec:
  type: LoadBalancer
  selector:
    app: livezilla-web
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
