apiVersion: v1
kind: PersistentVolume
metadata:
  name: livezilla-web
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: livezilla-web
    fsType: ext4
